services:
  bg-crop:
    build: .
    ports:
      - "19167:19167"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0
    device_requests:
      - driver: nvidia
        count: 1
        device_ids: ["0"]
        capabilities: ["gpu"]
